### ISSUE TITLE
Compilation on 32-bit system don't get though until I change `i64` to `i32`.

### ISSUE THREAD

**Issue by vi** [rust-gnome/gtk#84] opened 2015-05-19 01:28 UTC
```
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/src/widgets/vte_terminal.rs:32:94: 32:111 error: mismatched types:
 expected `i32`,
    found `i64`
(expected i32,
    found i64) [E0308]
/home/vi/home/rust/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/src/widgets/vte_terminal.rs:32         unsafe { ffi::vte_terminal_feed(self.pointer, data.as_bytes().as_ptr() as *const i8, data.len() as i64) }
```

**Comment by GuillaumeGomez** [comment] 2015-05-19 07:51
The problem is quite simple actually, it just needs an `as c_int` cast when passing the variable to the C function.

**Comment by gkoz** [comment] 2015-05-19 10:40
This issue is not applicable here, it's in this fork: https://github.com/oakes/gtk

**Comment by GuillaumeGomez** [comment] 2015-05-19 10:42
@gkoz: My answer remains good however haha. I close this issue then !

**Closed by GuillaumeGomez** 2015-05-19 10:42 UTC
